name = "Seven Oaks 4"
author = "Koruudo"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c94650d9ee8f8835a22ee73d00c2f99404cba7a310c1e9cc81e7079efc9adaa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
[options.curseforge]
release-type = "release"
[options.modrinth]
version-type = "release"
