name = "Seven Oaks 4"
author = "Koruudo"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a87476f6d48314518498ebfec34e56b8f679212bdb96b9a103ce284e33ac831b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
[options.curseforge]
release-type = "release"
[options.modrinth]
version-type = "release"
