name = "Seven Oaks 4"
author = "Koruudo"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d5543265bcf1a1d73a028dce857da2bb26c564a1a439a07b0ba89ed07ef893a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
[options.curseforge]
release-type = "release"
[options.modrinth]
version-type = "release"
